### ISSUE TITLE
Add community files to template generatoin

### ISSUE THREAD

**Issue by jscharber** [pavedroad-io/roadctl#5]
Today, we include community files in the YAMLs definitions but we do not create them.

Add them to the template creation process.  Only files listed are to be included in templates that are generated.

```
community:
  community-files:
  - {name: CODE_OF_CONDUCT.md, path: ., src: templatedir}
  - {name: CONTRIBUTING.md, path: ., src: templatedir}
  - {name: COVERNANCE.md, path: ., src: templatedir}
  - {name: MEETING.md, path: ., src: templatedir}
  - {name: OWNERS.md, path: ., src: templatedir}
  - {name: SECURITY.md, path: ., src: templatedir}
  - {md5: '123123123123123123231', name: SUPPORT.md, path: ., src: 'git-api://templates.pavedroad.io/templates/oos/support.md'}
  - {name: ROADMAP.md, path: ., src: 'https://w.pavedroad.io/templates/roadmap.md'}
  - {name: SECURITY.md, path: ., src: templatedir}
  - {name: ROADMAP.md, path: ., src: 'https://w.pavedroad.io/templates/roadmap.md'}
  description: list of community files to include
```
